port: 8080
sslPort: 8443

# No password required to add/delete if public
public: false

# Password for administration UI if not public
adminPass: change_me

# Database name/path
database: gluecan.sqlite

# Optional keystore for HTTPS
keystore:
  path: ~
  password: ~
